version: "3.9"

networks:
  lnet:
    name: "lnet"
    driver: "bridge"
    internal: true
  inet:
    name: "inet"
    driver: "bridge"
    internal: false

services:
  mksdb-mariadb:
    image: "mariadb"
    networks:
      - inet
      - lnet
    ports:
      - "3307:3306"
    environment:
      - MYSQL_DATABASE=schlager
      - MYSQL_USER=schlager
      - MYSQL_PASSWORD=zorofzoftumev
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    command: "mariadbd --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci"
    volumes:
      - "./mariadb-data:/var/lib/mysql"

  mksdb-php:
    build:
      context: .
    networks:
      - lnet
      - inet
    ports:
      - "8081:80"
      - "8050:8050"
    volumes:
      - "../:/var/www/proj"
      - "../web:/var/www/html"